### ISSUE TITLE
\ottava error

### ISSUE THREAD

**Issue by martinjaroszewicz** [wbsoft/python-ly#50]
Error when using \ottava # 
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_export/__init__.py", line 64, in exportMusicXML
  File "ly/musicxml/lymus2musxml.pyc", line 93, in parse_text
  File "ly/musicxml/lymus2musxml.pyc", line 106, in parse_document
  File "ly/musicxml/lymus2musxml.pyc", line 120, in parse_tree
  File "ly/musicxml/lymus2musxml.pyc", line 132, in parse_nodes
  File "ly/musicxml/lymus2musxml.pyc", line 512, in SchemeItem
  File "ly/musicxml/ly2xml_mediator.pyc", line 656, in new_ottava
ValueError: invalid literal for int() with base 10: 'mixed'

**Comment by martinjaroszewicz** [comment]
It's either \ottava or \override TimeSignature...
in \layout


[lilypondMxmlError.txt](https://github.com/wbsoft/python-ly/files/48117/lilypondMxmlError.txt)

**Comment by PeterBjuhr** [comment]
> It's either \ottava or \override TimeSignature...

It's `\override TimeSignature #'stencil = ##f`, but this should of course not be interpreted as an ottava marking! :)

**Comment by PeterBjuhr** [comment]
@martinjaroszewicz Thank for reporting! This should be fixed now. And I found a few other things related to the ottava handling. Unfortunately this doesn't necessarily mean that your file now exports correctly. Please don't hesitate to open additional issues!
