### ISSUE TITLE
AttributeError: 'list' object has no attribute 'obj_list'

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/python-ly#69]
Reported by a Frescobaldi user:
```
Frescobaldi: 2.18.2 -- Python: 2.7.11 -- python-ly: 0.9.3 -- Qt: 4.8.7 -- PyQt: 4.11.4 -- sip: 4.17 -- poppler: 0.39.0 -- python-poppler-qt: 0.24.0 -- OS: Darwin-14.5.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
  File "ly/musicxml/lymus2musxml.pyc", line 146, in musicxml
  File "ly/musicxml/xml_objs.pyc", line 78, in __init__
  File "ly/musicxml/xml_objs.pyc", line 99, in iterate_part
  File "ly/musicxml/xml_objs.pyc", line 106, in iterate_bar
AttributeError: 'list' object has no attribute 'obj_list'

```

**Comment by Volcarnious** [comment]
I have the same problem.
Steps to reproduce:
download for example https://upload.wikimedia.org/score/g/8/g8oardeeamxcszami4u1grvoemfvvtc/g8oardee.ly and save as test.ly

Using
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
and typing:
`python -m ly musicxml test.ly > test.musicxml`

gives me the same error

```
(C:\dev\Anaconda3) C:\Users\User1\Documents\dir1>python -m ly musicxml "test.ly"
Unknown command: \small
Unknown command: \break
Warning: SchemeList not implemented!
'ParseSource' object has no attribute 'SchemeList'
Unknown command: \break
Unknown command: \break
Unknown command: \small
Unknown command: \small
Warning: LayoutContext not implemented!
'ParseSource' object has no attribute 'LayoutContext'
Warning: SchemeList not implemented!
'ParseSource' object has no attribute 'SchemeList'
Traceback (most recent call last):
  File "C:\dev\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\dev\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\Anaconda3\lib\site-packages\ly\__main__.py", line 6, in <module>
    sys.exit(main())
  File "C:\dev\Anaconda3\lib\site-packages\ly\cli\main.py", line 299, in main
    c.run(options, cursor, output)
  File "C:\dev\Anaconda3\lib\site-packages\ly\cli\command.py", line 236, in run
    xml = writer.musicxml()
  File "C:\dev\Anaconda3\lib\site-packages\ly\musicxml\lymus2musxml.py", line 171, in musicxml
    self.mediator.score, self.musxml, self.mediator.divisions)
  File "C:\dev\Anaconda3\lib\site-packages\ly\musicxml\xml_objs.py", line 80, in __init__
    self.iterate_part(p)
  File "C:\dev\Anaconda3\lib\site-packages\ly\musicxml\xml_objs.py", line 101, in iterate_part
    self.iterate_bar(bar)
  File "C:\dev\Anaconda3\lib\site-packages\ly\musicxml\xml_objs.py", line 107, in iterate_bar
    if len(bar.obj_list) > 1:  # Prevents empty measures from being made
AttributeError: 'list' object has no attribute 'obj_list'

```

**Comment by wvengen** [comment]
I'm getting this error with something as simple as this:
```lilypond
\score {
  <<
    \new Voice { a1 }
    \addlyrics { \lyricmode { Foo } }
  >>
  \layout { }
}
```

When removing the lyrics, it works.

**Comment by wvengen** [comment]
May be related to #57.

**Comment by bmjcode** [comment]
I think the root cause here is that the MusicXML code doesn't currently process `\addlyrics` blocks. #180 fixes the exception, but this will need further work to actually be able to export lyrics.
