### ISSUE TITLE
python-ly-0.9.4.tar.gz on https://pypi.python.org/pypi/python-ly fails tests

### ISSUE THREAD

**Issue by anthonyfok** [wbsoft/python-ly#70]
When I tried to update the python-ly Debian package to 0.9.4 using source tarball downloaded https://pypi.python.org/pypi/python-ly, I ran into the following test error:

```
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:184: cd /build/python-ly-0.9.4/.pybuild/pythonX.Y_3.5/build; python3.5 -m unittest discover -v 
runTest (ly.test.test_document.TestEditEnd) ... ERROR
runTest (ly.test.test_document.TestEditStart) ... ok

======================================================================
ERROR: runTest (ly.test.test_document.TestEditEnd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-ly-0.9.4/.pybuild/pythonX.Y_3.5/build/ly/test/test_document.py", line 23, in runTest
    d[-1] = "E"
  File "/build/python-ly-0.9.4/.pybuild/pythonX.Y_3.5/build/ly/document.py", line 230, in __exit__
    self.apply_changes()
  File "/build/python-ly-0.9.4/.pybuild/pythonX.Y_3.5/build/ly/document.py", line 485, in apply_changes
    s.text = s.text[:start - s.position] + e.text[end - e.position:]
AttributeError: 'NoneType' object has no attribute 'text'

----------------------------------------------------------------------
Ran 2 tests in 0.011s

FAILED (errors=1)
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: cd /build/python-ly-0.9.4/.pybuild/pythonX.Y_3.5/build; python3.5 -m unittest discover -v 
```

Running `python3 setup.py test` yields the same error, but `python setup.py test` (with Python 2.7) is fine.

This led me to discover that python-0.9.4.tar.gz on PyPI is rather different from v0.9.4.tar.gz / HEAD on GitHub:

* `python-0.9.4/tests/test_xml.py` (GitHub)
* `python-0.9.4/ly/test/test_document.py` dated June 2015 (PyPI)

Is the discrepancy intentional?

**Comment by jgarte** [comment]
Hi,

Any updates on this?

I learned about this through nixpkgs:

https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/python-ly/default.nix#L17

**Comment by alerque** [comment]
The PyPi releases are not even the latest, see #163 for background. Switch to GH sources for the current release, then see if tests run.

**Comment by alerque** [comment]
The test suite from the current release on GH does not run either, but it is for other reasons than shown in this issue. See #153 for that.

**Comment by fedelibre** [comment]
The tests are building fine in the latest release (0.9.10).

If you find any issue, please open a new one.
