### ISSUE TITLE
'Document' has no attribute 'copy'

### ISSUE THREAD

**Issue by mtarenskeen** [wbsoft/python-ly#75]
I'm using Lilypond 2.19.47 and python-ly 0.9.4 on Fedora 24. If I try to convert any minimal example from ly to musicxml I'm getting this error. (Sorry if this has already been reported)

> Traceback (most recent call last):
  File "/usr/bin/ly", line 4, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/python_ly-0.9.4-py2.7.egg/ly/cli/main.py", line 288, in main
    c.run(options, cursor, output)
  File "/usr/lib/python2.7/site-packages/python_ly-0.9.4-py2.7.egg/ly/cli/command.py", line 221, in run
    writer.parse_document(cursor.document, absolute)
  File "/usr/lib/python2.7/site-packages/python_ly-0.9.4-py2.7.egg/ly/musicxml/lymus2musxml.py", line 114, in parse_document
    doc = ly_doc.copy()
AttributeError: 'Document' object has no attribute 'copy'

**Comment by wbsoft** [comment]
Hi, please check if your installation is correct, the Document class in `/usr/lib/python2.7/site-packages/python_ly-0.9.4-py2.7.egg/ly/document.py` should have a `copy()` method when `python-ly-0.9.4` is installed correctly. I can't reproduce.

Sorry for replying so late! I've been very busy lately...

**Comment by mtarenskeen** [comment]
Hmm. Strange. Maybe there is some kind of conflict in my Fedora distribution. I have installed python-ly Fedora packages for both Python 2 and Python 3. If I run "python3 /usr/bin/ly musicxml example.ly" it seems to work fine, but if I run "ly musicxml example.ly" or "python /usr/bin/ly musicxml example.ly" python 2.7 is used, and then I am getting the error. But the copy() method is in the file as you describe as far as I can see. I will do more testing, but maybe you can give me a clue already from what I describe?

**Comment by mtarenskeen** [comment]
What version of Fedora are you using? I think in very latest versions Python3 is the default python, so python=python3.x

In slightly older Fedora versions python=python2.7. 

Maybe your problem is related to this change in the Fedora distro?
