### ISSUE TITLE
MusicXML export fails on "check_simultan self.sections.pop()"

### ISSUE THREAD

**Issue by ExecutorElassus** [wbsoft/python-ly#76]
I have the following file
[transkription kayser 6. messe d-moll - flattened.ly.zip](https://github.com/wbsoft/python-ly/files/546247/transkription.kayser.6.messe.d-moll.-.flattened.ly.zip)

Export to MusicXML fails with the following error:

``Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
    writer.parse_text(doc.toPlainText())
  File "/usr/lib64/python2.7/site-packages/ly/musicxml/lymus2musxml.py", line 102, in parse_text
    self.parse_document(doc)
  File "/usr/lib64/python2.7/site-packages/ly/musicxml/lymus2musxml.py", line 119, in parse_document
    self.parse_tree(mustree)
  File "/usr/lib64/python2.7/site-packages/ly/musicxml/lymus2musxml.py", line 133, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/lib64/python2.7/site-packages/ly/musicxml/lymus2musxml.py", line 145, in parse_nodes
    func_call(m)
  File "/usr/lib64/python2.7/site-packages/ly/musicxml/lymus2musxml.py", line 624, in End
    self.mediator.check_simultan()
  File "/usr/lib64/python2.7/site-packages/ly/musicxml/ly2xml_mediator.py", line 293, in check_simultan
    self.sections.pop()
IndexError: pop from empty list``

(the \includes in that file are all layout/font options. The entire file tree can be found [here](https://git.openlilylib.org/bfsc/kayser/blob/master/messen/messe%206/transkription%20kayser%206.%20messe%20d-moll.ly)).

What is going wrong here? Is there some issue of formatting that isn't being correctly interpreted?

Thanks for the help

**Comment by uliska** [comment]
Note that this file can only be compiled in the original contexts as otherwise the includes cannot be resolved.

I suspected this failed include could be the reason but when placing the flattened file in the original context a) it became compilable and b) the MusicXML export fails with the same message. So this is *not* the issue.

The other thing is that I tried that with `python-ly` from Git (where the OP obviously has the packaged version), and the error is the same. So *that* isn't a reason either.

**Comment by mtarenskeen** [comment]
I bumped into this bug when trying a very simple test:
1. create a very simple **minimal.ly** test with for example only { c' d' e' f' }
2. ly musicxml minimal.ly -o minimal.musicxml
3. musicxml2ly minimal.musicxml -o minimal2.ly
4. ly musicxml minimal2.ly -o minimal2.musicxml

Unknown command: \mergeDifferentlyDottedOn
Unknown command: \mergeDifferentlyHeadedOn
Warning: End not implemented!
'NoneType' object has no attribute 'merge_voice'
Traceback (most recent call last):
  File "/usr/bin/ly", line 4, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/ly/cli/main.py", line 288, in main
    c.run(options, cursor, output)
  File "/usr/lib/python3.7/site-packages/ly/cli/command.py", line 221, in run
    writer.parse_document(cursor.document, absolute)
  File "/usr/lib/python3.7/site-packages/ly/musicxml/lymus2musxml.py", line 119, in parse_document
    self.parse_tree(mustree)
  File "/usr/lib/python3.7/site-packages/ly/musicxml/lymus2musxml.py", line 133, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/lib/python3.7/site-packages/ly/musicxml/lymus2musxml.py", line 145, in parse_nodes
    func_call(m)
  File "/usr/lib/python3.7/site-packages/ly/musicxml/lymus2musxml.py", line 624, in End
    self.mediator.check_simultan()
  File "/usr/lib/python3.7/site-packages/ly/musicxml/ly2xml_mediator.py", line 293, in check_simultan
    self.sections.pop()
IndexError: pop from empty list

**Comment by mtarenskeen** [comment]
As a workaround I changed line 293 in ly2xml_mediator.py. I am not enough of a Python programmer if this makes any sense, but it worked for me now.

```
        # self.sections.pop()
        if self.sections:
            self.sections.pop()

```

**Comment by shoorick** [comment]
The same situation in 2022. As written in previous comment it's possible to patch `/usr/lib/python3/dist-packages/ly/musicxml/ly2xml_mediator.py` — different lines but the same code

```diff
301c301,302
<         self.sections.pop()
---
>         if self.sections:
>             self.sections.pop()
```

**Comment by fedelibre** [comment]
It's probably a workaround to avoid the error, but not the best solution to fix the underlying bug. I'm not able to help.
