### ISSUE TITLE
i wanted to reinstall pyton-ly but not sure how

### ISSUE THREAD

**Issue by seanincali** [wbsoft/python-ly#87]
I'm running frescobaldi 2.20 And when I tried to open the following ly file from this [link](http://www.mutopiaproject.org/ftp/CarcassiM/O1/carcassi-op1n02/carcassi-op1n02.ly) it threw a bunch of errors. 

So I tried to export it out to musicxml from within frescobaldi, then it throws the following error. 

Traceback (most recent call last):
File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_export_init_.py", line 65, in exportMusicXML
writer.parse_text(doc.toPlainText())
File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 102, in parse_text
File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 119, in parse_document
File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 126, in parse_tree
File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 148, in parse_nodes
IOError: [Errno 9] Bad file descriptor

Will reinstalling python-ly solve this problem? If so, how do I do that so that it works with frescobaldi? Or is there a link where I can learn to use script with python-ly so i can convert the ly to musicxml? 

Thanks for any help

**Comment by fedelibre** [comment]
This is not the best place to ask for help. You'd better ask on [Frescobaldi group](https://groups.google.com/forum/#!forum/frescobaldi) and paste the "bunch of errors" when you open the file.

No problem here with Frescobaldi 3 (from master) on Linux.

**Comment by seanincali** [comment]
Ok. I already have. Thank you.
